CMS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataLayer;

namespace CMS.Controllers
{
    public class HomeController : Controller
    {
        CmsContext db = new CmsContext();
        private IPageRepository pageRepository;

        public HomeController()
            {
            pageRepository = new PageRepository(db);
            }
        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult ShowInSlider()
        {
            return PartialView(pageRepository.ShowInSlider());
        }
    }
}

CMS/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataLayer;

namespace CMS.Controllers
{
    public class NewsController : Controller
    {
        CmsContext db = new CmsContext();
        private IPageGroupRepostiory pageGroupRepostiory;
        private IPageRepository pageRepository;
        private IPageCommentRepository pageCommentRepository;

        public NewsController()
        {
            pageGroupRepostiory = new PageGroupRepository(db);
            pageRepository = new PageRepository(db);
            pageCommentRepository = new PageCommentRepository(db);
        }
        // GET: News
        public ActionResult ShowGroups()
        {
            return PartialView(pageGroupRepostiory.GetGroupsForView());
        }
        public ActionResult ShowGroupsInDropDown()
        {
            return PartialView(pageGroupRepostiory.GetAllGroups());
        }
        public ActionResult TopNews()
        {
            return PartialView(pageRepository.TopNews());
        }
        public ActionResult LastNews()
        {
            return PartialView(pageRepository.LastNews());
        }

        [Route("Archive")]
        public ActionResult Archive()
        {
            return View(pageRepository.LastNews());
        }
        [Route("Group/{id}/{title}")]
        public ActionResult ShowNewsByGroupId(int id, string title)
        {
            ViewBag.Name = title;
            return View(pageRepository.ShowPageByGroupId(id));
        }
        [Route("News/{id}")]
        public ActionResult ShowNews(int id)
        {
            var news = pageRepository.GetPageById(id);

            if (news == null)
            {
                return HttpNotFound();
            }

            news.visit += 1;
            pageRepository.UpdatePage(news);
            pageRepository.save();

            return View(news);

        }
        public ActionResult AddComment(int id, string name, string email, string comment)
        {
            PageComment addcomment = new PageComment()
            {
                CreateDate = DateTime.Now,
                PageID = id,
                Name = name,
                Email = email,
            };

            pageCommentRepository.AddComment(addcomment);

            return PartialView("ShowComments",id);
        }
        public ActionResult ShowComments(int id)
        {
            return PartialView(pageCommentRepository.GetCommentsByNewsId(id));
        }
    }
}

CMS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CMS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CMS/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@Html.Action("ShowInSlider")
@Html.Action("LastNews","News")

CMS/Views/Home/ShowInSlider.cshtml
@model IEnumerable<DataLayer.Page>



<!-- slider -->
<div class="news-slider border-radius">
    <div id="slider-one" class="owl-carousel">

        @foreach (var item in Model)
        {
            <div class="item">
                <img src="~/PageIMG/@item.ImageName">
                <div class="left-side">
                    <h2> <a href="/News/@item.PageID">@item.Title</a> </h2>
                    <p>
                        @item.ShortDescription
                    </p>
                    <span> <i class="fa fa-calendar"></i> انتشار : @item.CreateDate</span>
                </div>
                <div class="clearfix"></div>
            </div>
        }

    </div>
    <a href="/Archive" class="news-archive"> <i class="icons icon-doc-1"></i> آرشیو کامل خبرها </a>
</div>
<!-- End slider -->